name: turist_data
description: "LRCLIB Flutter App - Clean Architecture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.6.0
  # Dependency Injection
  get_it: ^7.7.0
  google_generative_ai: ^0.3.2
  flutter_rating_bar: ^4.0.0

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Networking
  http: ^1.2.0
  dio: ^5.8.0+1
  connectivity_plus: ^6.0.2

  # Functional Programming
  dartz: ^0.10.1



  # Local Storage
  shared_preferences: ^2.2.2

  # Routing
  go_router: ^13.0.0

  # Maps
  flutter_map: ^6.0.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/top_wave.png
    - assets/images/bottom_wave.png
